### ISSUE TITLE
/uuid/recycle-bin not working

### ISSUE THREAD

**Issue by Knorrke** [serlo/serlo.org#193]
Error:
```
Nachricht:

    Discussion\Entity\Comment provides an instance of null

Stapelüberwachung:

    #0 /usr/local/apache2/htdocs/src/module/Authorization/src/Authorization/Service/AuthorizationService.php(73): Authorization\Assertion\InstanceAssertion->assert(Object(Authorization\Result\AuthorizationResult), Object(Discussion\Entity\Comment))
    #1 /usr/local/apache2/htdocs/src/module/Authorization/src/Authorization/Service/AuthorizationService.php(51): Authorization\Service\AuthorizationService->assertStrategy(Object(Authorization\Assertion\InstanceAssertion), Object(Authorization\Result\AuthorizationResult), Object(Discussion\Entity\Comment))
    #2 /usr/local/apache2/htdocs/src/vendor/zf-commons/zfc-rbac/src/ZfcRbac/View/Helper/IsGranted.php(56): Authorization\Service\AuthorizationService->isGranted('discussion.comm...', Object(Discussion\Entity\Comment))
    #3 [internal function]: ZfcRbac\View\Helper\IsGranted->__invoke('discussion.comm...', Object(Discussion\Entity\Comment))
    #4 /usr/local/apache2/htdocs/src/data/classes.php.cache(85): call_user_func_array(Object(ZfcRbac\View\Helper\IsGranted), Array)
    #5 /usr/local/apache2/htdocs/src/module/Ui/templates/uuid/recycle-bin.phtml(47): Zend\View\Renderer\PhpRenderer->__call('isGranted', Array)
    #6 /usr/local/apache2/htdocs/src/data/classes.php.cache(85): include('/usr/local/apac...')
    #7 /usr/local/apache2/htdocs/src/data/classes.php.cache(85): Zend\View\Renderer\PhpRenderer->render(NULL)
    #8 /usr/local/apache2/htdocs/src/data/classes.php.cache(85): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
    #9 /usr/local/apache2/htdocs/src/data/classes.php.cache(85): Zend\View\View->renderChildren(Object(Zend\View\Model\ViewModel))
    #10 /usr/local/apache2/htdocs/src/vendor/zendframework/zendframework/library/Zend/Mvc/View/Http/DefaultRenderingStrategy.php(103): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
    #11 [internal function]: Zend\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Zend\Mvc\MvcEvent))
    #12 /usr/local/apache2/htdocs/src/data/classes.php.cache(2): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
    #13 /usr/local/apache2/htdocs/src/data/classes.php.cache(2): Zend\EventManager\EventManager->triggerListeners('render', Object(Zend\Mvc\MvcEvent), Array)
    #14 /usr/local/apache2/htdocs/src/data/classes.php.cache(2): Zend\EventManager\EventManager->trigger('render', Object(Zend\Mvc\MvcEvent))
    #15 /usr/local/apache2/htdocs/src/data/classes.php.cache(2): Zend\Mvc\Application->completeRequest(Object(Zend\Mvc\MvcEvent))
    #16 /usr/local/apache2/htdocs/src/public/index.php(47): Zend\Mvc\Application->run()
    #17 {main}
```

**Comment by kulla** [comment]
Additional information: This bug does not occurs for logged in users:

![2020-01-09-191056_1614x828_scrot](https://user-images.githubusercontent.com/1327215/72093047-f372be80-3313-11ea-93db-8bdcac7d731d.png)

**Comment by inyono** [comment]
Can't reproduce, works for me
