### ISSUE TITLE
frontend: 500 on /mitmachen

### ISSUE THREAD

**Issue by inyono** [serlo/serlo.org#235]
See https://de.serlo-staging.dev/mitmachen

```
TypeError: Cannot read property 'values' of undefined
    at compile (/usr/src/app/packages/public/frontend/.next/serverless/pages/__content.js:69347:60)
    at Text.getLeaves (/usr/src/app/packages/public/frontend/.next/serverless/pages/__content.js:69459:7)
    at serializeNode (/usr/src/app/packages/public/frontend/.next/serverless/pages/__content.js:175891:25)
    at /usr/src/app/packages/public/frontend/.next/serverless/pages/__content.js:54751:46
    at List.__iterate (/usr/src/app/packages/public/frontend/.next/serverless/pages/__content.js:53941:13)
    at IndexedIterable.mappedSequence.__iterateUncached (/usr/src/app/packages/public/frontend/.next/serverless/pages/__content.js:54750:23)
    at seqIterate (/usr/src/app/packages/public/frontend/.next/serverless/pages/__content.js:52339:16)
    at IndexedIterable.IndexedSeq.__iterate (/usr/src/app/packages/public/frontend/.next/serverless/pages/__content.js:52055:14)
    at IndexedIterable.toArray (/usr/src/app/packages/public/frontend/.next/serverless/pages/__content.js:55993:23)
    at List [as constructor] (/usr/src/app/packages/public/frontend/.next/serverless/pages/__content.js:53800:62)
```

- [ ] Error shouldn't be show to the user
- [ ] @inyono: handle that in key-value store

**Comment by Entkenntnis** [comment]
This error-page should definitely not be shown to the user. We could check for "__next/_error“ and/or response code and show something more decent, like "something went wrong" ... probably a good idea to fix this in renderComponent for now?

**Comment by kulla** [comment]
Seems to be fixed in the meanwhile...
