### ISSUE TITLE
Fix e2e tests

### ISSUE THREAD

**Issue by kulla** [serlo/serlo.org#477]
Today I get the following error while running `yarn test:e2e`.

```
$ ▶ yarn test:e2e                                                                         
yarn run v1.22.4
$ jest --config ./jest.config-e2e.js --maxWorkers 1
TypeError: Cannot read property 'onlyChanged' of undefined
    at _default (/home/kulla/workspace/serlo/serlo.org/node_modules/jest-cli/node_modules/@jest/core/build/getChangedFilesPromise.js:49:20)                                               
    at /home/kulla/workspace/serlo/serlo.org/node_modules/jest-cli/node_modules/@jest/core/build/cli/index.js:296:71                                                                      
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/home/kulla/workspace/serlo/serlo.org/node_modules/jest-cli/node_modules/@jest/core/build/cli/index.js:108:24)                                                 
    at _next (/home/kulla/workspace/serlo/serlo.org/node_modules/jest-cli/node_modules/@jest/core/build/cli/index.js:128:9)                                                               
    at /home/kulla/workspace/serlo/serlo.org/node_modules/jest-cli/node_modules/@jest/core/build/cli/index.js:133:7                                                                       
    at new Promise (<anonymous>)
    at /home/kulla/workspace/serlo/serlo.org/node_modules/jest-cli/node_modules/@jest/core/build/cli/index.js:125:12                                                                      
    at _run (/home/kulla/workspace/serlo/serlo.org/node_modules/jest-cli/node_modules/@jest/core/build/cli/index.js:374:20)                                                               
    at /home/kulla/workspace/serlo/serlo.org/node_modules/jest-cli/node_modules/@jest/core/build/cli/index.js:178:13
```

**Comment by inyono** [comment]
`rm -rf node_modules && yarn`

**Comment by kulla** [comment]
> rm -rf node_modules && yarn

Thx

**Comment by ahcl7** [comment]
> `rm -rf node_modules && yarn`

You saved my day!
